"use client";
import { X } from "lucide-react"; import { useState } from "react"; import { toast } from "sonner";
export function AuthModal({mode,onClose,onSwitch}:{mode:"login"|"register"|null;onClose:()=>void;onSwitch:(m:"login"|"register")=>void}){
 const [busy,setBusy]=useState(false); if(!mode)return null;
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const data=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch(`/api/auth/${mode}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});const json=await r.json();setBusy(false);if(!r.ok)return toast.error(json.error||"Не удалось продолжить");toast.success(mode==="login"?"С возвращением!":"Аккаунт создан");location.href=json.redirect||"/dashboard/client";}
 return <div className="fixed inset-0 z-50 grid place-items-center bg-ink/40 p-4 backdrop-blur-sm" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="card relative w-full max-w-md p-8"><button className="absolute right-5 top-5" onClick={onClose}><X/></button><div className="eyebrow">Добро пожаловать</div><h2 className="mt-2 font-serif text-3xl font-bold">{mode==="login"?"Войти в Cosmetos":"Создать аккаунт"}</h2><p className="mt-2 text-sm text-black/55">{mode==="login"?"Ваши записи и любимые мастера уже ждут.":"Запись к специалисту займёт меньше минуты."}</p>
 <form className="mt-6 grid gap-3" onSubmit={submit}>{mode==="register"&&<><input className="input" name="firstName" placeholder="Имя" required/><select className="input" name="role"><option value="CLIENT">Я клиент</option><option value="MASTER">Я мастер</option><option value="SALON_OWNER">Я владелец салона</option></select></>}<input className="input" name="email" type="email" placeholder="Email" required/><input className="input" name="password" type="password" placeholder="Пароль" required/><button disabled={busy} className="btn-primary mt-2">{busy?"Подождите…":mode==="login"?"Войти":"Зарегистрироваться"}</button></form>
 <button className="mt-5 w-full text-sm text-rose" onClick={()=>onSwitch(mode==="login"?"register":"login")}>{mode==="login"?"Нет аккаунта? Зарегистрироваться":"Уже есть аккаунт? Войти"}</button></div></div>
}
