"use client";
import Image from "next/image";
import Link from "next/link";
import { Heart, Search, Star } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { getMedia } from "@/lib/media";
export function Catalog({slug,items,initial=""}:{slug:string;items:string[];initial?:string}){const [all,setAll]=useState(items);const [query,setQuery]=useState(initial);const [price,setPrice]=useState("0");const [rating,setRating]=useState("0");const [favorites,setFavorites]=useState<Set<string>>(new Set());useEffect(()=>{if(slug==="categories")fetch("/api/services").then(r=>r.json()).then(x=>setAll(Array.from(new Set([...items,...x.map((s:{name:string})=>s.name)])) as string[])).catch(()=>null);fetch("/api/favorites").then(r=>r.ok?r.json():[]).then((rows:{entityType:string;entityId:string}[])=>setFavorites(new Set(rows.filter(x=>x.entityType===slug).map(x=>x.entityId)))).catch(()=>null)},[slug,items]);const shown=useMemo(()=>all.map((title,i)=>({title,i,price:1200+i*700,rating:i%2?4.8:4.9})).filter(x=>x.title.toLowerCase().includes(query.trim().toLowerCase())&&(!+price||x.price<=+price)&&x.rating>=+rating),[all,query,price,rating]);
 async function favorite(x:{title:string;i:number}){const id=String(x.i+1);const image=getMedia(slug,x.i);const r=await fetch("/api/favorites",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({entityType:slug,entityId:id,title:x.title,subtitle:"Сохранено из каталога",imageUrl:image,href:`/${slug}/${id}`})});const data=await r.json();if(r.status===401)return toast.error(data.error);setFavorites(old=>{const next=new Set(old);data.favorite?next.add(id):next.delete(id);return next});toast.success(data.favorite?"Добавлено в избранное":"Удалено из избранного")}
 return <><div className="card mb-8 grid gap-3 md:grid-cols-5"><label className="relative md:col-span-2"><Search className="absolute left-4 top-3.5 text-black/35" size={18}/><input className="input pl-11" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск по словам из карточек"/></label><select className="input" value={price} onChange={e=>setPrice(e.target.value)}><option value="0">Любая цена</option><option value="2000">до 2 000 ₽</option><option value="5000">до 5 000 ₽</option></select><select className="input" value={rating} onChange={e=>setRating(e.target.value)}><option value="0">Любой рейтинг</option><option value="4.5">от 4.5</option><option value="4.9">от 4.9</option></select><div className="grid place-items-center rounded-2xl bg-blush text-sm">{shown.length} результатов</div></div>
 {shown.length?<div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{shown.map(x=>{const active=favorites.has(String(x.i+1));return <article key={x.title} className="card group p-3 transition hover:-translate-y-1"><Link href={`/${slug}/${x.i+1}`}><Image src={getMedia(slug,x.i)} width={550} height={365} alt={x.title} className="aspect-[16/10] w-full rounded-[22px] object-cover"/><div className="p-3"><div className="flex items-center justify-between"><span className="flex items-center gap-1 rounded-full bg-cream px-3 py-1 text-xs font-bold"><Star size={12} fill="#a85f70" className="text-rose"/>{x.rating}</span><b>{x.price.toLocaleString("ru-RU")} ₽</b></div><h2 className="mt-5 font-serif text-2xl font-bold">{x.title}</h2><p className="mt-2 text-sm text-black/50">Свободные окна сегодня · проверено Cosmetos</p></div></Link><button onClick={()=>favorite(x)} className={active?"btn mb-2 ml-3 bg-rose text-white":"btn-light mb-2 ml-3"}><Heart size={17} fill={active?"currentColor":"none"}/>{active?"В избранном":"В избранное"}</button></article>})}</div>:<div className="card py-16 text-center"><h2 className="font-serif text-2xl font-bold">Ничего не найдено</h2><p className="mt-2 text-black/45">Попробуйте другое слово или сбросьте фильтры.</p></div>}</>
}
