"use client";
import Image from "next/image"; import Link from "next/link"; import { usePathname } from "next/navigation"; import { useEffect,useState } from "react"; import { Bell, CalendarDays, ChartNoAxesCombined, ChevronRight, CircleDollarSign, Heart, LayoutDashboard, LogOut, Megaphone, MessageSquare, Scissors, Settings, ShieldCheck, Star, Tags, UserRound, Users } from "lucide-react"; import { toast } from "sonner";
const nav:Record<string,[string,string,typeof Star][]> = {
 client:[["Обзор","",LayoutDashboard],["Мои записи","bookings",CalendarDays],["Избранное","favorites",Heart],["Мои отзывы","reviews",Star],["Профиль","profile",UserRound],["Безопасность","security",ShieldCheck],["Уведомления","notifications",Bell]],
 master:[["Обзор","",LayoutDashboard],["Профиль мастера","profile",UserRound],["Услуги и цены","services",Scissors],["Расписание","schedule",CalendarDays],["Записи клиентов","bookings",Users],["Отзывы","reviews",Star],["Реклама","campaigns",Megaphone],["Статистика","stats",ChartNoAxesCombined],["Настройки","settings",Settings]],
 salon:[["Обзор","",LayoutDashboard],["Сотрудники","employees",Users],["Услуги","services",Scissors],["Расписание","schedule",CalendarDays],["Записи","bookings",CalendarDays],["Финансы","finance",CircleDollarSign],["Акции и промокоды","promocodes",Tags],["Роли сотрудников","roles",ShieldCheck],["Настройки","settings",Settings]],
 admin:[["Обзор","",LayoutDashboard],["Модерация","moderation",ShieldCheck],["Пользователи","users",Users],["Мастера","masters",UserRound],["Салоны","salons",Scissors],["Категории","categories",Tags],["Записи","bookings",CalendarDays],["Отзывы","reviews",Star],["Реклама","ads",Megaphone],["Жалобы","complaints",MessageSquare]]
};
export function DashboardShell({role,section,name}:{role:string;section:string;name:string}){const pathname=usePathname();const items=nav[role];const active=items.find(x=>x[1]===section)||items[0];
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});location.href="/"}
 return <div className="container py-8"><div className="grid gap-7 lg:grid-cols-[250px_1fr]"><aside className="card h-fit p-3"><div className="p-4"><div className="text-xs text-black/45">Личный кабинет</div><b>{name}</b></div><nav className="grid gap-1">{items.map(([label,url,Icon])=><Link key={label} href={`/dashboard/${role}/${url}`} className={`flex items-center gap-3 rounded-2xl px-4 py-3 text-sm ${pathname===`/dashboard/${role}/${url}`||(!url&&pathname===`/dashboard/${role}`)?"bg-ink text-white":"hover:bg-blush"}`}><Icon size={17}/>{label}</Link>)}</nav><button onClick={logout} className="mt-3 flex w-full items-center gap-3 border-t border-black/5 px-4 pt-4 text-sm text-rose"><LogOut size={17}/>Выйти</button></aside>
 <div><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="eyebrow">{role==="admin"?"Управление платформой":"Сегодня отличный день"}</div><h1 className="mt-1 font-serif text-4xl font-bold">{active[0]}</h1></div><button className="btn-primary" onClick={()=>toast.success("Изменения сохранены")}>+ Добавить</button></div><DashboardContent section={section} role={role}/></div></div></div>}
function DashboardContent({section,role}:{section:string;role:string}){
 if(!section)return <><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Записи сегодня","8","+14%"],["Выручка","36 400 ₽","+8%"],["Новые отзывы","12","4.9 ★"],["Заполняемость","78%","+5%"]].map(x=><div className="card" key={x[0]}><span className="text-sm text-black/45">{x[0]}</span><div className="mt-3 text-3xl font-black">{x[1]}</div><span className="mt-2 inline-block rounded-full bg-green-50 px-2 py-1 text-xs text-green-700">{x[2]}</span></div>)}</div><Panel title="Ближайшие записи"/><div className="mt-5 grid gap-5 md:grid-cols-2"><Panel title="Динамика недели" mini/><Panel title="Быстрые действия" mini/></div></>;
 if(section==="favorites"||section==="bookings")return <DynamicList section={section}/>;
 const form=["profile","services","schedule","settings","security","promocodes"].includes(section);
 return <div className="mt-7">{form?<Editor section={section}/>:<Panel title={title(section)} admin={role==="admin"}/>}</div>
}
function title(s:string){return ({bookings:"Все записи",favorites:"Избранные специалисты",reviews:"Отзывы клиентов",notifications:"Центр уведомлений",employees:"Команда салона",finance:"Финансовые операции",roles:"Роли и доступы",campaigns:"Рекламные кампании",stats:"Статистика",moderation:"Очередь модерации",users:"Пользователи",masters:"Мастера",salons:"Салоны",categories:"Категории услуг",ads:"Рекламные кампании",complaints:"Жалобы"} as Record<string,string>)[s]||"Раздел"}
function Panel({title,mini,admin}:{title:string;mini?:boolean;admin?:boolean}){const rows=mini?["Пн","Вт","Ср"]:admin?["Анна Смирнова · мастер","Élan Beauty Club · салон","Отзыв #2048"]:["Анна · Маникюр","Мария · Окрашивание","Елена · Консультация","Дарья · Коррекция бровей"];return <div className="card mt-5 overflow-hidden p-0"><div className="flex items-center justify-between border-b border-black/5 p-5"><b>{title}</b><button className="text-sm text-rose">Смотреть все</button></div>{rows.map((x,i)=><div key={x} className="grid grid-cols-[1fr_auto_auto] items-center gap-4 border-b border-black/5 px-5 py-4 last:border-0"><div><b className="text-sm">{x}</b><p className="text-xs text-black/40">{i%2?"Завтра, 12:30":"Сегодня, 16:00"}</p></div><span className={`rounded-full px-3 py-1 text-xs ${i===2?"bg-amber-50 text-amber-700":"bg-green-50 text-green-700"}`}>{i===2?"Ожидает":"Подтверждено"}</span><button onClick={()=>toast.success("Действие выполнено")}><ChevronRight size={18}/></button></div>)}</div>}
function Editor({section}:{section:string}){if(section==="services")return <ServiceEditor/>;function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();toast.success("Настройки сохранены")}return <form className="card grid gap-5" onSubmit={submit}><div className="grid gap-5 md:grid-cols-2"><label>Название / имя<input className="input mt-2" defaultValue="Cosmetos Professional"/></label><label>Город<input className="input mt-2" list="profile-cities" placeholder="Начните вводить город"/><datalist id="profile-cities">{["Москва","Санкт-Петербург","Новосибирск","Екатеринбург","Казань","Нижний Новгород","Красноярск","Челябинск","Самара","Уфа","Ростов-на-Дону","Краснодар","Омск","Воронеж","Пермь"].map(x=><option key={x} value={x}/>)}</datalist></label><label>Начало рабочего дня<input className="input mt-2" type="time" defaultValue="10:00"/></label><label>Конец рабочего дня<input className="input mt-2" type="time" defaultValue="20:00"/></label></div><label>Описание<textarea className="input mt-2 min-h-28" defaultValue={`Настройки раздела «${section}». Расскажите клиентам самое важное.`}/></label><div className="flex justify-end"><button className="btn-primary">Сохранить изменения</button></div></form>}
function ServiceEditor(){const [services,setServices]=useState<{id:string;name:string}[]>([]);useEffect(()=>{fetch("/api/services").then(r=>r.json()).then(setServices)},[]);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const r=await fetch("/api/services",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(form)))});const x=await r.json();if(!r.ok)return toast.error(x.error||"Не удалось добавить услугу");setServices(old=>[...old,{id:x.id,name:x.name}]);form.reset();toast.success("Услуга добавлена и доступна в поиске")}return <div className="grid gap-5"><form className="card grid gap-5" onSubmit={submit}><h2 className="font-serif text-2xl font-bold">Новая услуга</h2><div className="grid gap-5 md:grid-cols-3"><label>Название<input className="input mt-2" name="name" required placeholder="Например, SPA-уход"/></label><label>Цена, ₽<input className="input mt-2" name="price" type="number" min="1" required/></label><label>Длительность, мин.<input className="input mt-2" name="durationMin" type="number" min="15" step="15" defaultValue="60" required/></label></div><button className="btn-primary justify-self-end">Добавить услугу</button></form><div className="card"><h2 className="font-serif text-2xl font-bold">Услуги в каталоге</h2><div className="mt-4 grid gap-2">{services.map(x=><div key={x.id} className="flex items-center justify-between rounded-2xl bg-cream px-4 py-3"><span>{x.name}</span><span className="text-xs text-green-700">Активна</span></div>)}</div></div></div>}
function DynamicList({section}:{section:string}){const [rows,setRows]=useState<Record<string,unknown>[]|null>(null);useEffect(()=>{fetch(section==="favorites"?"/api/favorites":"/api/bookings").then(r=>r.json()).then(x=>setRows(Array.isArray(x)?x:[])).catch(()=>setRows([]))},[section]);if(rows===null)return <div className="card mt-7 animate-pulse">Загружаем данные…</div>;if(!rows.length)return <div className="card mt-7 py-16 text-center"><Heart className="mx-auto text-rose"/><h2 className="mt-4 font-serif text-2xl font-bold">{section==="favorites"?"В избранном пока пусто":"Записей пока нет"}</h2><p className="mt-2 text-black/45">Сохранённые карточки и созданные записи появятся здесь автоматически.</p></div>;return <div className="mt-7 grid gap-4">{rows.map(row=>section==="favorites"?<Link href={String(row.href)} key={String(row.id)} className="card flex items-center gap-5 p-4">{row.imageUrl?<Image src={String(row.imageUrl)} width={120} height={80} alt="" className="h-20 w-28 rounded-2xl object-cover"/>:null}<div><b>{String(row.title)}</b><p className="text-sm text-black/45">{String(row.subtitle||"Открыть карточку")}</p></div><ChevronRight className="ml-auto"/></Link>:<Link href={`/booking/${String(row.id)}`} key={String(row.id)} className="card flex items-center justify-between"><div><b>Запись на {new Date(String(row.startsAt)).toLocaleString("ru-RU")}</b><p className="text-sm text-black/45">Стоимость: {String(row.price)} ₽ · статус: {String(row.status)}</p></div><ChevronRight/></Link>)}</div>}
