import Link from "next/link"; import { notFound } from "next/navigation"; import { ArrowRight, SlidersHorizontal, Star } from "lucide-react"; import { publicPages } from "@/lib/content";
export default async function PublicPage({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<Record<string,string>>}){
 const {slug}=await params; const query=await searchParams; const page=publicPages[slug]; if(!page)notFound();
 const catalog=["masters","salons","categories","promotions","articles"].includes(slug);
 return <><section className="border-b border-black/5 bg-blush/40 py-16"><div className="container"><div className="eyebrow">{page.eyebrow}</div><h1 className="mt-3 max-w-3xl font-serif text-5xl font-bold">{page.title}</h1><p className="mt-4 max-w-2xl text-lg text-black/55">{page.description}</p></div></section>
 <section className="container py-12">{catalog&&<form className="card mb-8 grid gap-3 md:grid-cols-5"><input className="input md:col-span-2" name="q" defaultValue={query.service||query.q} placeholder="Услуга или название"/><select className="input" name="price"><option>Любая цена</option><option>до 2 000 ₽</option><option>до 5 000 ₽</option></select><select className="input" name="rating"><option>Любой рейтинг</option><option>от 4.5</option><option>только 5.0</option></select><button className="btn-primary"><SlidersHorizontal size={16}/>Применить</button></form>}
 <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{page.items.map((item,i)=><Link href={catalog?`/${slug}/${i+1}`:"#details"} key={item} className="card group min-h-48 transition hover:-translate-y-1"><div className="flex items-start justify-between"><span className="grid size-12 place-items-center rounded-2xl bg-blush text-xl">{["✦","♡","◌","◇"][i%4]}</span>{catalog&&<span className="flex items-center gap-1 rounded-full bg-cream px-3 py-1 text-xs font-bold"><Star size={12} fill="#a85f70" className="text-rose"/>4.{9-i%2}</span>}</div><h2 className="mt-8 font-serif text-2xl font-bold">{item}</h2><p className="mt-2 text-sm leading-6 text-black/50">{catalog?"Свободные окна сегодня · проверено Cosmetos":"Подробная информация и полезные ответы внутри раздела."}</p><span className="mt-5 flex items-center gap-2 text-sm font-bold text-rose">Подробнее <ArrowRight size={15}/></span></Link>)}</div>
 {!catalog&&<div id="details" className="card mt-8"><h2 className="font-serif text-2xl font-bold">Остались вопросы?</h2><p className="mt-2 text-black/50">Напишите нам — команда Cosmetos поможет разобраться.</p><Link href="/support" className="btn-primary mt-5">Связаться с поддержкой</Link></div>}</section></>
}
